### ISSUE TITLE
[off-topic] iTerm question

### ISSUE THREAD

**Issue by mattmrsa** [githubteacher/nov-2015-developers#89]
@githubteacher how do you get iTerm to display the last x commands in that bottom pane?

**Comment by githubteacher** [comment]
It's a combination of a few things: ⌘⇧D splits the screen horizontally (⌘D does a vertical split). At that point, I _basically_ am `tail`ing history in the lower portion of the screen. We have actually built a [couple of scripts](https://github.com/github/training-utils/blob/master/historytailbash) to manage this, but it's mostly window-dressing.

There's a little work involved in setting up shared history between sessions and it varies based on your shell -- otherwise, the split windows will each have their own, separate histories -- [here's a good discussion](http://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows) around doing this for `bash`.

Hope that helps!

**Comment by mattmrsa** [comment]
Thanks!
